{% set name = "swift-sim" %}
{% set version = "0.9.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/swift-sim-{{ version }}.tar.gz
  sha256: ba139b13bfce87869bc6151cf69d2f27bc07268403e32f4426b22244fe3cec3e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - pip
    - python
    - numpy
  run:
    - python
    - websockets
    - {{ pin_compatible('numpy') }}
    - spatialmath-python

test:
  imports:
    - swift
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jhavl/swift
  summary: A Python/Javascript Visualiser
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - jhavl
