{% set name = "swift-sim" %}
{% set version = "0.9.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jhavl/swift/archive/v{{ version }}.tar.gz
  sha256: d38c924c041fa01c98fa815d96f5f49fa578108508e482b4f67197deae7a43ef

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - pip
    - python
    - numpy
  run:
    - python
    - websockets
    - {{ pin_compatible('numpy') }}
    - spatialmath-python
    - spatialgeometry >=0.1.0

test:
  imports:
    - swift
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jhavl/swift
  summary: A Python/Javascript Visualiser
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - jhavl
