{% set name = "swift-sim" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jhavl/swift/archive/v{{ version }}.tar.gz
  sha256: 874c62653581666be5bea3d11ad9621c897937472cf86f0bcbba2dab344c57a1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - pip
    - python
    - numpy
  run:
    - python
    - websockets
    - {{ pin_compatible('numpy') }}
    - spatialmath-python
    - spatialgeometry >=1.0.0

test:
  imports:
    - swift
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jhavl/swift
  summary: A Python/Javascript Visualiser
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - jhavl
