{% set name = "swift-sim" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jhavl/swift/archive/v{{ version }}.tar.gz
  sha256: 08ae9f9d498d0f6e5e8f5325ed814b344a6e0139d9ab09539d16a9000f7d7f9c

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - pip
    - python
    - numpy
  run:
    - python
    - websockets
    - spatialmath-python
    - spatialgeometry >=1.0.0

test:
  imports:
    - swift
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jhavl/swift
  summary: A Python/Javascript Visualiser
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - jhavl
